
CREATE TABLE STUDENT(SID INT, SNAME VARCHAR(25), LOCATION VARCHAR(25))

INSERT INTO STUDENT VALUES(101, 'Xlib', 'Havana')
INSERT INTO STUDENT VALUES(102, 'Bob', 'Nepal')
INSERT INTO STUDENT VALUES(103, 'Ram', 'Colombo')
INSERT INTO STUDENT VALUES(104, 'Baba', 'Mexico')
INSERT INTO STUDENT VALUES(105, 'Rajesh', 'Moscow',12)

/*Shows Values from the table*/
SELECT SNAME, SID FROM STUDENT
SELECT * FROM STUDENT

--DELETe values form the table where, where specifies the  condition
DELETE FROM STUDENT WHERE SID = 104

--TRUNCATe vanishes all the table data
TRUNCATE TABLE STUDENT

--Affects data in the  table
UPDATE STUDENT SET LOCATION = 'Merar' WHERE SID = 101

--ADDs/ delete coloumn to the table 
ALTER TABLE STUDENT ADD AGE INT

UPDATE STUDENT SET AGE = 19 WHERE SID = 101
UPDATE STUDENT SET AGE = 29 WHERE SID = 102
UPDATE STUDENT SET AGE = 69 WHERE SID = 103
UPDATE STUDENT SET AGE = 29 WHERE SID = 104
UPDATE STUDENT SET AGE = 99 WHERE SID = 105

--Adding Primary key in Student table
ALTER TABLE STUDENT ALTER COLUMN SID int NOT NULL;
ALTER TABLE STUDENT ADD PRIMARY KEY(SID);


--Adding Primary key in Student table
ALTER TABLE STUDENT ALTER COLUMN SID int NOT NULL;
ALTER TABLE STUDENT ADD PRIMARY KEY(SID);


SELECT * FROM STUDENT FOR XML PATH('STUDENT'), ROOT('STUDENT') 
SELECT * FROM STUDENT FOR XML RAW 
SELECT * FROM STUDENT FOR XML AUTO
SELECT * FROM STUDENT FOR XML EXPLICIT


----No  clue what is going on from here

--Saving a XML file
DECLARE @XMLCONTENT AS XML
SET @XMLCONTENT = 
(
	SELECT * FROM STUDENT FOR XML PATH('STUDENT'), ROOT('STUDENT')
)
SELECT @XMLCONTENT

--Create table
CREATE TABLE STUDENTDETAILS(SID INT, SNAME VARCHAR(25), LOCATION VARCHAR(25),AGE INT)
SELECT * FROM STUDENTDETAILS
GO
CREATE PROCEDURE INSTERDETAILS1
@XMLDATA XML
AS
BEGIN
SET NOCOUNT ON;
INSERT INTO STUDENTDETAILS(SID,SNAME,LOCATION,AGE)
SELECT X.value('SID[1]','INT') AS SID,
X.value('SNAME[1]','VARCHAR(25)') AS SNAME,
X.value('LOCATION[1]','VARCHAR(25)') AS LOCATION,
X.value('AGE[1]','INT') AS AGE
FROM @XMLDATA.nodes('//STUDENT') XMLDATA(X)
END
GO

DECLARE @XMLDATA XML
SET @XMLDATA = '<STUDENT>
<STUDENT>
<SID>101</SID>
<SNAME>XLIB</SNAME>
<LOCATION>HAVANA</LOCATION>
<AGE>16</AGE>
</STUDENT>
</STUDENT>'

EXEC @XMLDATA
SELECT * FROM STUDENTDETAILS

--Querring the data
declare @xlmstudent as XML =
'<STUDENT>
<STUDENTS ROLLNO="300" NAME="SCOTT"/>
<STUDENTS ROLLNO="100" NAME="STEVE"/>
<STUDENTS ROLLNO="200" NAME="CODY"/>
</STUDENT>'
--single row
--SELECT @xlmstudent.query('STUDENT/STUDENTS')
--multiple rows
SELECT T.C.query('.') AS result
SELECT @xlmstudent.query('STUDENT/STUDENTS')T(C)

--from Jenifer to All Attendees:
declare @xlmstudent as XML =
'<STUDENT>
<STUDENTS ROLLNO="300" NAME="SCOTT"/>
<STUDENTS ROLLNO="100" NAME="STEVE"/>
<STUDENTS ROLLNO="200" NAME="CODY"/>
</STUDENT>'
SELECT
STUDENT.C.value('@ROLLNO','int') as ROLLNO,
STUDENT.C.value('@NAME','VARCHAR(25)') as NAME
FROM @xlmstudent.nodes('STUDENT/STUDENTS[@ROLLNO > 100]') STUDENT(C)

--
