
CREATE TABLE STUDENT(SID INT, SNAME VARCHAR(25), LOCATION VARCHAR(25))

INSERT INTO STUDENT VALUES(101, 'Xlib', 'Havana')
INSERT INTO STUDENT VALUES(102, 'Bob', 'Nepal')
INSERT INTO STUDENT VALUES(103, 'Ram', 'Colombo')
INSERT INTO STUDENT VALUES(104, 'Baba', 'Mexico')
INSERT INTO STUDENT VALUES(105, 'Rajesh', 'Moscow',12)

/*Shows Values from the table*/
SELECT SNAME, SID FROM STUDENT
SELECT * FROM STUDENT

--DELETe values form the table where, where specifies the  condition
DELETE FROM STUDENT WHERE SID = 104

--TRUNCATe vanishes all the table data
TRUNCATE TABLE STUDENT

--Affects data in the  table
UPDATE STUDENT SET LOCATION = 'Merar' WHERE SID = 101

--ADDs/ delete coloumn to the table 
ALTER TABLE STUDENT ADD AGE INT

UPDATE STUDENT SET AGE = 19 WHERE SID = 101
UPDATE STUDENT SET AGE = 29 WHERE SID = 102
UPDATE STUDENT SET AGE = 69 WHERE SID = 103
UPDATE STUDENT SET AGE = 29 WHERE SID = 104
UPDATE STUDENT SET AGE = 99 WHERE SID = 105

--Adding Primary key in Student table
ALTER TABLE STUDENT ALTER COLUMN SID int NOT NULL;
ALTER TABLE STUDENT ADD PRIMARY KEY(SID);
